#!/bin/bash


while getopts "u:w:f:" option; do
    case "${option}" in
        u) url=${OPTARG};;
        w) wordlist=${OPTARG};;
        f) filter=${OPTARG};;
        ?) echo -e "Invalid option: Use -u <url> or -w [<wordlist>]"; exit 1;;
    esac
done


# Error Handler
[[ -z "$url" ]] && { echo -e "Error: \e[31m-u \e[33m<url>\e[0m is required" >&2; exit 1; }
[[ -z "$wordlist" ]] && { echo -e "Error: \e[31m-w \e[33m<wordlist>\e[0m is required" >&2; exit 1; }

#Wordlist Handler.
if [[ -n "$wordlist" ]]; then
    if [[ ! -f "$wordlist" ]]; then
        echo "Error: Wordlist file '$wordlist' not found!" >&2
        exit 1
    fi
    WORDLIST="$wordlist"
else
    WORDLIST=""
fi


if [[ -n "$WORDLIST" ]]; then
    echo "==========================================="
    echo " Reading wordlist: $WORDLIST "
    echo " Total words: $(wc -l < "$WORDLIST") "
    echo "==========================================="
    echo "[*] research begins ... "
    
    FILTER="$filter"
    counter=1
    while IFS= read -r word; do
                          
        if [ -n "$word" ]; then        
                status_code=$(curl -sI "$url$word" | awk '/HTTP/ {print $2}' | tail -l)                       
        fi
        
        [[ -z "$status_code" ]] && status_code="" 
                                  
        if [ "$status_code" = "200" ]; then
            line="STATUS CODE: \e[1;32m$status_code\e[0m | $url\e[1;34m$word\e[0m"
        elif [ -z "$status_code" ]; then            
            line="ERROR: \e[1;33mNothing found ...\e[0m | $url\e[1;34m$word\e[0m"
        elif [ "$status_code" = "404" ]; then           
            line="STATUS CODE: \e[1;31m$status_code\e[0m | $url\e[1;34m$word\e[0m"
        else            
            line="STATUS CODE: \e[1;34m$status_code\e[0m | $url\e[1;34m$word\e[0m"
        fi
        
        if [[ -z "$FILTER" || "$status_code" =~ ^($FILTER)$ ]]; then
            echo -e "$line"
        fi
        
    done < "$WORDLIST"
    echo "[*] Research Done !"
fi
